add_newline = false
command_timeout = 800
format = "$directory$os$git_branch$git_status$character"

[os]
disabled = false

[os.symbols]
Windows = "☠️ "

[directory]
truncation_length = 3
truncate_to_repo = false
read_only = " [ro]"

[git_branch]
symbol = ""
format = "$symbol$branch"

[git_status]
format = "$all_status$ahead_behind"

[character]
success_symbol = "[❯](bold)"
error_symbol = "[❯](bold)"
vimcmd_symbol = "[❮](bold)"